"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.data = void 0;
exports.data = [
    {
        key: 0,
        facilityType: "Import Facilities Bundle",
        children: [
            {
                key: 11,
                facilityType: "Import LCs - Secured",
                facilityId: 1122334455,
                limitType: "Outer",
                existingLimitsCurrency: "USD",
                existingLimits: "500.00",
                proposedLimitsCurrency: "USD",
                proposedLimits: "500.00",
                maxTenor: "1 Year",
                status: "Unchanged",
            },
            {
                key: 12,
                facilityType: "Disc Payement of ...",
                facilityId: 223344,
                limitType: "Inner",
                existingLimitsCurrency: "USD",
                existingLimits: "500.00",
                proposedLimitsCurrency: "USD",
                proposedLimits: "500.00",
                maxTenor: "1 Year",
                status: "Unchanged",
            },
            {
                key: 13,
                facilityType: "Import Invoice financing",
                facilityId: 333333,
                limitType: "Inner",
                existingLimitsCurrency: "USD",
                existingLimits: "500.00",
                proposedLimitsCurrency: "USD",
                proposedLimits: "500.00",
                maxTenor: "1 Year",
                status: "Unchanged",
            },
            {
                key: 14,
                facilityType: "Custom Entry 1",
                facilityId: 11111,
                limitType: "Inner",
                existingLimitsCurrency: "USD",
                existingLimits: "500.00",
                proposedLimitsCurrency: "USD",
                proposedLimits: "500.00",
                maxTenor: "1 Year",
                status: "Unchanged",
            },
            {
                key: 15,
                facilityType: "Custom Entry 2",
                facilityId: 222222,
                limitType: "Inner",
                existingLimitsCurrency: "USD",
                existingLimits: "500.00",
                proposedLimitsCurrency: "USD",
                proposedLimits: "500.00",
                maxTenor: "1 Year",
                status: "Changed",
            },
            {
                key: 16,
                facilityType: "Custom Entry 3",
                facilityId: 33333,
                limitType: "Inner",
                existingLimitsCurrency: "USD",
                existingLimits: "500.00",
                proposedLimitsCurrency: "USD",
                proposedLimits: "500.00",
                maxTenor: "1 Year",
                status: "Unchanged",
            },
        ],
    },
    {
        key: 2,
        facilityType: "Overdraft 1",
        children: [
            {
                key: 21,
                facilityType: "Import LCs - Secured",
                facilityId: 21212121,
                limitType: "Outer",
                existingLimitsCurrency: "USD",
                existingLimits: "500.00",
                proposedLimitsCurrency: "USD",
                proposedLimits: "500.00",
                maxTenor: "1 Year",
                status: "Unchanged",
            },
        ],
    },
    {
        key: 3,
        facilityType: "Overdraft 2",
        children: [
            {
                key: 31,
                facilityType: "Import Invoice financing",
                facilityId: 313131,
                limitType: "Inner",
                existingLimitsCurrency: "USD",
                existingLimits: "500.00",
                proposedLimitsCurrency: "USD",
                proposedLimits: "500.00",
                maxTenor: "1 Year",
                status: "Changed",
            },
        ],
    },
];
